language: go

go:
  - 1.13.10

before_install:
  - curl -L https://go.kubebuilder.io/dl/2.3.1/linux/amd64 | tar -xz -C /usr/local/
  - ln -s /usr/local/kubebuilder_2.3.1_linux_amd64/bin/kubebuilder /usr/local/bin/kubebuilder

script:
  - make test
  - make manager
