
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - crd.projectcalico.org
  resources:
  - bgppeers
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - route-reflector.calico-route-reflector-operator.mhmxs.github.com
  resources:
  - routereflectorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route-reflector.calico-route-reflector-operator.mhmxs.github.com
  resources:
  - routereflectorconfigs/status
  verbs:
  - get
  - patch
  - update
