apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: routereflectorconfig-viewer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: routereflectorconfig-viewer-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
