apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: DATASTORE_TYPE
              value: "etcdv3"
            - name: ETCD_ENDPOINTS
              valueFrom:
                secretKeyRef: 
                  name: etcd-config
                  key: ETCD_ENDPOINTS
            - name: ETCD_DISCOVERY_SRV
              valueFrom:
                secretKeyRef:
                  name: etcd-config
                  key: ETCD_DISCOVERY_SRV
            - name: ETCD_USERNAME
              valueFrom:
                secretKeyRef:
                  name: etcd-config
                  key: ETCD_USERNAME
            - name: ETCD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: etcd-config
                  key: ETCD_PASSWORD
            - name: ETCD_KEY_FILE
              value: "/etc/etcd/ETCD_KEY_FILE"
            - name: ETCD_CERT_FILE
              value: "/etc/etcd/ETCD_CERT_FILE"
            - name: ETCD_CA_CERT_FILE
              value: "/etc/etcd/ETCD_CA_CERT_FILE"